---
- name: Install MySQL
  hosts: test-vm's
  become: yes

  tasks:
     - name: install mysql
       apt:
           name: mysql-server
           state: latest

- name: Install nginx
  hosts: test-vm's
  become: yes
  
  tasks:
     - name: install nginx
       apt:
           name: nginx
           state: latest
